import os
from pathlib import Path
from shutil import rmtree


def cleanup(settings: dict) -> None:
    """Removes the leftover files generated by the script or ffmpeg from the working directory."""
    print('\ncleaning up...')
    tmpfile_list = ['IntroOutroList.txt', 'log.json', 'ffmpeg2pass-0.log']
    for tmp in tmpfile_list:
        try:
            os.remove(tmp)
        except FileNotFoundError:
            print(f"The file {tmp} does not exist.")
        except PermissionError:
            print(f"Insufficient permissions to delete the file {tmp}.")
        except IsADirectoryError:
            print(f"{tmp} is a directory, not a file.")
        except OSError as e:
            print(f"Error deleting file {tmp}: {e.strerror}")

    if Path(settings['tmp_folder']).exists() and not settings['keep_tmp_files']:
        tmpcleanup(settings)


def tmpcleanup(settings: dict) -> None:
    try:
        rmtree(settings['tmp_folder'])
    except FileNotFoundError:
        print(f"\nError cleaning up temp directory: {settings['tmp_folder']} does not exist.")
    except PermissionError:
        print(f"\nError cleaning up temp directory: Insufficient permissions to delete {settings['tmp_folder']}.")
    except OSError as e:
        print(f"\nError cleaning up temp directory: {e.strerror}")


def CreateTempFolder(settings: dict) -> None:
    """Creates the temporary folder used for chunk-based encoding and audio extraction.
    If the folder already exists, it will be wiped first."""
    directories = [settings['tmp_folder'], Path(settings['tmp_folder']) / 'prepared', Path(settings['tmp_folder']) / 'converted']

    for directory in directories:
        if Path(directory).exists():
            tmpcleanup(settings)
        os.mkdir(directory)


if __name__ == '__main__':
    print('This file should not be run as a standalone script!')
